### ISSUE TITLE
Refactor to us `if`

### ISSUE THREAD

**Issue by azranel** [Haradd/Looks-Tasty#10]
https://github.com/Haradd/Looks-Tasty/blob/fd0d9ac5c14bed199923c4b3204fb16969cc18c1/app/decorators/review_decorator.rb#L15-L16

`unless` is always hard to read, to be honest. Please, change it into if statements.

For first conditional, you can check if `current_user` is `nil` with `#nil?` method.

**Comment by Haradd** [comment]
Done
