### ISSUE TITLE
Refactor to use service object

### ISSUE THREAD

**Issue by azranel** [Haradd/Looks-Tasty#11]
https://github.com/Haradd/Looks-Tasty/blob/fd0d9ac5c14bed199923c4b3204fb16969cc18c1/app/controllers/users_controller.rb#L19-L36

This is a really nice example to refactor into the service object. Try to leave only code responsible for rendering and redirect in the controller and put rest of it into the service object.

**Comment by Haradd** [comment]
Thanks a lot! ;)
I've just made it here 
https://github.com/Haradd/Looks-Tasty/commit/f0adafc5cb63c6c61036b865fd5ebb9a1e58860d
