### ISSUE TITLE
Move method definitions lowers in recipe model

### ISSUE THREAD

**Issue by azranel** [Haradd/Looks-Tasty#7]
https://github.com/Haradd/Looks-Tasty/blob/fd0d9ac5c14bed199923c4b3204fb16969cc18c1/app/models/recipe.rb#L5-L14

Place definition methods below validations, associations and other ActiveRecord DSL. It just looks better and it's more standard way of writing code 😄

**Comment by Haradd** [comment]
Done :+1:
